source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BingMapsiOSSampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BingMapsiOSSampleApp
  pod 'MicrosoftMapsSDK', '~> 0.1.0'
end
