source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'BingMapsSearchSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BingMapsSearchSample
  pod 'MicrosoftMapsSDK', '~> 1.2.0'
end
